[package]
name = "leetcode-rust"
version = "0.1.0"
authors = ["zhiluniao <huangshunle_gxu@163.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
rand = "0.8.5"
lazy_static = "1.4.0"
itertools = "0.10.1"
